version: '3'

services:
  workspace:
    container_name: devcontainer_sample_workspace
    image: node:20-slim
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"